// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package rearm

import (
	"context"
	"encoding/json"

	"github.com/Khan/genqlient/graphql"
)

// ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult includes the requested fields of the GraphQL type DeclarativeApplyResult.
type ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult struct {
	ApplyResultFields `json:"-"`
}

// GetKind returns ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult.Kind, and is useful for accessing the field via an interface.
func (v *ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult) GetKind() DeclarativeKind {
	return v.ApplyResultFields.Kind
}

// GetDryRun returns ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult.DryRun, and is useful for accessing the field via an interface.
func (v *ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult) GetDryRun() bool {
	return v.ApplyResultFields.DryRun
}

// GetSpecHash returns ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult.SpecHash, and is useful for accessing the field via an interface.
func (v *ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult) GetSpecHash() string {
	return v.ApplyResultFields.SpecHash
}

// GetCreated returns ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult.Created, and is useful for accessing the field via an interface.
func (v *ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult) GetCreated() int {
	return v.ApplyResultFields.Created
}

// GetUpdated returns ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult.Updated, and is useful for accessing the field via an interface.
func (v *ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult) GetUpdated() int {
	return v.ApplyResultFields.Updated
}

// GetUnchanged returns ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult.Unchanged, and is useful for accessing the field via an interface.
func (v *ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult) GetUnchanged() int {
	return v.ApplyResultFields.Unchanged
}

// GetArchived returns ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult.Archived, and is useful for accessing the field via an interface.
func (v *ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult) GetArchived() int {
	return v.ApplyResultFields.Archived
}

// GetErrors returns ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult.Errors, and is useful for accessing the field via an interface.
func (v *ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult) GetErrors() int {
	return v.ApplyResultFields.Errors
}

// GetChanges returns ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult.Changes, and is useful for accessing the field via an interface.
func (v *ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult) GetChanges() []*ApplyResultFieldsChangesDeclarativeChange {
	return v.ApplyResultFields.Changes
}

func (v *ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult
		graphql.NoUnmarshalJSON
	}
	firstPass.ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.ApplyResultFields)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult struct {
	Kind DeclarativeKind `json:"kind"`

	DryRun bool `json:"dryRun"`

	SpecHash string `json:"specHash"`

	Created int `json:"created"`

	Updated int `json:"updated"`

	Unchanged int `json:"unchanged"`

	Archived int `json:"archived"`

	Errors int `json:"errors"`

	Changes []*ApplyResultFieldsChangesDeclarativeChange `json:"changes"`
}

func (v *ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult) __premarshalJSON() (*__premarshalApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult, error) {
	var retval __premarshalApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult

	retval.Kind = v.ApplyResultFields.Kind
	retval.DryRun = v.ApplyResultFields.DryRun
	retval.SpecHash = v.ApplyResultFields.SpecHash
	retval.Created = v.ApplyResultFields.Created
	retval.Updated = v.ApplyResultFields.Updated
	retval.Unchanged = v.ApplyResultFields.Unchanged
	retval.Archived = v.ApplyResultFields.Archived
	retval.Errors = v.ApplyResultFields.Errors
	retval.Changes = v.ApplyResultFields.Changes
	return &retval, nil
}

// ApplyBranchesResponse is returned by ApplyBranches on success.
type ApplyBranchesResponse struct {
	// Declarative apply of the Branches slice for one component / product (API key, write access on the
	// org). Idempotent, keyed by branch name. Branches absent from the spec follow Settings.declarativePrune.
	ApplyBranchesProgrammatic *ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult `json:"applyBranchesProgrammatic"`
}

// GetApplyBranchesProgrammatic returns ApplyBranchesResponse.ApplyBranchesProgrammatic, and is useful for accessing the field via an interface.
func (v *ApplyBranchesResponse) GetApplyBranchesProgrammatic() *ApplyBranchesApplyBranchesProgrammaticDeclarativeApplyResult {
	return v.ApplyBranchesProgrammatic
}

// ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult includes the requested fields of the GraphQL type DeclarativeApplyResult.
type ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult struct {
	ApplyResultFields `json:"-"`
}

// GetKind returns ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult.Kind, and is useful for accessing the field via an interface.
func (v *ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult) GetKind() DeclarativeKind {
	return v.ApplyResultFields.Kind
}

// GetDryRun returns ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult.DryRun, and is useful for accessing the field via an interface.
func (v *ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult) GetDryRun() bool {
	return v.ApplyResultFields.DryRun
}

// GetSpecHash returns ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult.SpecHash, and is useful for accessing the field via an interface.
func (v *ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult) GetSpecHash() string {
	return v.ApplyResultFields.SpecHash
}

// GetCreated returns ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult.Created, and is useful for accessing the field via an interface.
func (v *ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult) GetCreated() int {
	return v.ApplyResultFields.Created
}

// GetUpdated returns ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult.Updated, and is useful for accessing the field via an interface.
func (v *ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult) GetUpdated() int {
	return v.ApplyResultFields.Updated
}

// GetUnchanged returns ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult.Unchanged, and is useful for accessing the field via an interface.
func (v *ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult) GetUnchanged() int {
	return v.ApplyResultFields.Unchanged
}

// GetArchived returns ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult.Archived, and is useful for accessing the field via an interface.
func (v *ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult) GetArchived() int {
	return v.ApplyResultFields.Archived
}

// GetErrors returns ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult.Errors, and is useful for accessing the field via an interface.
func (v *ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult) GetErrors() int {
	return v.ApplyResultFields.Errors
}

// GetChanges returns ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult.Changes, and is useful for accessing the field via an interface.
func (v *ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult) GetChanges() []*ApplyResultFieldsChangesDeclarativeChange {
	return v.ApplyResultFields.Changes
}

func (v *ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult
		graphql.NoUnmarshalJSON
	}
	firstPass.ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.ApplyResultFields)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult struct {
	Kind DeclarativeKind `json:"kind"`

	DryRun bool `json:"dryRun"`

	SpecHash string `json:"specHash"`

	Created int `json:"created"`

	Updated int `json:"updated"`

	Unchanged int `json:"unchanged"`

	Archived int `json:"archived"`

	Errors int `json:"errors"`

	Changes []*ApplyResultFieldsChangesDeclarativeChange `json:"changes"`
}

func (v *ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult) __premarshalJSON() (*__premarshalApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult, error) {
	var retval __premarshalApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult

	retval.Kind = v.ApplyResultFields.Kind
	retval.DryRun = v.ApplyResultFields.DryRun
	retval.SpecHash = v.ApplyResultFields.SpecHash
	retval.Created = v.ApplyResultFields.Created
	retval.Updated = v.ApplyResultFields.Updated
	retval.Unchanged = v.ApplyResultFields.Unchanged
	retval.Archived = v.ApplyResultFields.Archived
	retval.Errors = v.ApplyResultFields.Errors
	retval.Changes = v.ApplyResultFields.Changes
	return &retval, nil
}

// ApplyCatalogResponse is returned by ApplyCatalog on success.
type ApplyCatalogResponse struct {
	// Declarative apply of the Catalog slice (API key, write access on the org). Idempotent, keyed by
	// component name. dryRun computes the change set without writing.
	ApplyCatalogProgrammatic *ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult `json:"applyCatalogProgrammatic"`
}

// GetApplyCatalogProgrammatic returns ApplyCatalogResponse.ApplyCatalogProgrammatic, and is useful for accessing the field via an interface.
func (v *ApplyCatalogResponse) GetApplyCatalogProgrammatic() *ApplyCatalogApplyCatalogProgrammaticDeclarativeApplyResult {
	return v.ApplyCatalogProgrammatic
}

// ApplyResultFields includes the GraphQL fields of DeclarativeApplyResult requested by the fragment ApplyResultFields.
type ApplyResultFields struct {
	Kind      DeclarativeKind                              `json:"kind"`
	DryRun    bool                                         `json:"dryRun"`
	SpecHash  string                                       `json:"specHash"`
	Created   int                                          `json:"created"`
	Updated   int                                          `json:"updated"`
	Unchanged int                                          `json:"unchanged"`
	Archived  int                                          `json:"archived"`
	Errors    int                                          `json:"errors"`
	Changes   []*ApplyResultFieldsChangesDeclarativeChange `json:"changes"`
}

// GetKind returns ApplyResultFields.Kind, and is useful for accessing the field via an interface.
func (v *ApplyResultFields) GetKind() DeclarativeKind { return v.Kind }

// GetDryRun returns ApplyResultFields.DryRun, and is useful for accessing the field via an interface.
func (v *ApplyResultFields) GetDryRun() bool { return v.DryRun }

// GetSpecHash returns ApplyResultFields.SpecHash, and is useful for accessing the field via an interface.
func (v *ApplyResultFields) GetSpecHash() string { return v.SpecHash }

// GetCreated returns ApplyResultFields.Created, and is useful for accessing the field via an interface.
func (v *ApplyResultFields) GetCreated() int { return v.Created }

// GetUpdated returns ApplyResultFields.Updated, and is useful for accessing the field via an interface.
func (v *ApplyResultFields) GetUpdated() int { return v.Updated }

// GetUnchanged returns ApplyResultFields.Unchanged, and is useful for accessing the field via an interface.
func (v *ApplyResultFields) GetUnchanged() int { return v.Unchanged }

// GetArchived returns ApplyResultFields.Archived, and is useful for accessing the field via an interface.
func (v *ApplyResultFields) GetArchived() int { return v.Archived }

// GetErrors returns ApplyResultFields.Errors, and is useful for accessing the field via an interface.
func (v *ApplyResultFields) GetErrors() int { return v.Errors }

// GetChanges returns ApplyResultFields.Changes, and is useful for accessing the field via an interface.
func (v *ApplyResultFields) GetChanges() []*ApplyResultFieldsChangesDeclarativeChange {
	return v.Changes
}

// ApplyResultFieldsChangesDeclarativeChange includes the requested fields of the GraphQL type DeclarativeChange.
type ApplyResultFieldsChangesDeclarativeChange struct {
	ChangeFields `json:"-"`
}

// GetKind returns ApplyResultFieldsChangesDeclarativeChange.Kind, and is useful for accessing the field via an interface.
func (v *ApplyResultFieldsChangesDeclarativeChange) GetKind() DeclarativeKind {
	return v.ChangeFields.Kind
}

// GetName returns ApplyResultFieldsChangesDeclarativeChange.Name, and is useful for accessing the field via an interface.
func (v *ApplyResultFieldsChangesDeclarativeChange) GetName() string { return v.ChangeFields.Name }

// GetAction returns ApplyResultFieldsChangesDeclarativeChange.Action, and is useful for accessing the field via an interface.
func (v *ApplyResultFieldsChangesDeclarativeChange) GetAction() DeclarativeAction {
	return v.ChangeFields.Action
}

// GetFields returns ApplyResultFieldsChangesDeclarativeChange.Fields, and is useful for accessing the field via an interface.
func (v *ApplyResultFieldsChangesDeclarativeChange) GetFields() []string {
	return v.ChangeFields.Fields
}

// GetMessage returns ApplyResultFieldsChangesDeclarativeChange.Message, and is useful for accessing the field via an interface.
func (v *ApplyResultFieldsChangesDeclarativeChange) GetMessage() *string {
	return v.ChangeFields.Message
}

func (v *ApplyResultFieldsChangesDeclarativeChange) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*ApplyResultFieldsChangesDeclarativeChange
		graphql.NoUnmarshalJSON
	}
	firstPass.ApplyResultFieldsChangesDeclarativeChange = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.ChangeFields)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalApplyResultFieldsChangesDeclarativeChange struct {
	Kind DeclarativeKind `json:"kind"`

	Name string `json:"name"`

	Action DeclarativeAction `json:"action"`

	Fields []string `json:"fields"`

	Message *string `json:"message"`
}

func (v *ApplyResultFieldsChangesDeclarativeChange) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *ApplyResultFieldsChangesDeclarativeChange) __premarshalJSON() (*__premarshalApplyResultFieldsChangesDeclarativeChange, error) {
	var retval __premarshalApplyResultFieldsChangesDeclarativeChange

	retval.Kind = v.ChangeFields.Kind
	retval.Name = v.ChangeFields.Name
	retval.Action = v.ChangeFields.Action
	retval.Fields = v.ChangeFields.Fields
	retval.Message = v.ChangeFields.Message
	return &retval, nil
}

type AutoIntegrateState string

const (
	AutoIntegrateStateEnabled  AutoIntegrateState = "ENABLED"
	AutoIntegrateStateDisabled AutoIntegrateState = "DISABLED"
)

var AllAutoIntegrateState = []AutoIntegrateState{
	AutoIntegrateStateEnabled,
	AutoIntegrateStateDisabled,
}

type BranchSpecInput struct {
	Name                          string                         `json:"name"`
	Type                          *BranchType                    `json:"type"`
	VersionSchema                 *string                        `json:"versionSchema"`
	MarketingVersionSchema        *string                        `json:"marketingVersionSchema"`
	VcsBranch                     *string                        `json:"vcsBranch"`
	AutoIntegrate                 *AutoIntegrateState            `json:"autoIntegrate"`
	FindingAnalyticsParticipation *FindingAnalyticsParticipation `json:"findingAnalyticsParticipation"`
	Dependencies                  []*DependencySpecInput         `json:"dependencies,omitempty"`
	DependencyPatterns            []*DependencyPatternSpecInput  `json:"dependencyPatterns,omitempty"`
}

// GetName returns BranchSpecInput.Name, and is useful for accessing the field via an interface.
func (v *BranchSpecInput) GetName() string { return v.Name }

// GetType returns BranchSpecInput.Type, and is useful for accessing the field via an interface.
func (v *BranchSpecInput) GetType() *BranchType { return v.Type }

// GetVersionSchema returns BranchSpecInput.VersionSchema, and is useful for accessing the field via an interface.
func (v *BranchSpecInput) GetVersionSchema() *string { return v.VersionSchema }

// GetMarketingVersionSchema returns BranchSpecInput.MarketingVersionSchema, and is useful for accessing the field via an interface.
func (v *BranchSpecInput) GetMarketingVersionSchema() *string { return v.MarketingVersionSchema }

// GetVcsBranch returns BranchSpecInput.VcsBranch, and is useful for accessing the field via an interface.
func (v *BranchSpecInput) GetVcsBranch() *string { return v.VcsBranch }

// GetAutoIntegrate returns BranchSpecInput.AutoIntegrate, and is useful for accessing the field via an interface.
func (v *BranchSpecInput) GetAutoIntegrate() *AutoIntegrateState { return v.AutoIntegrate }

// GetFindingAnalyticsParticipation returns BranchSpecInput.FindingAnalyticsParticipation, and is useful for accessing the field via an interface.
func (v *BranchSpecInput) GetFindingAnalyticsParticipation() *FindingAnalyticsParticipation {
	return v.FindingAnalyticsParticipation
}

// GetDependencies returns BranchSpecInput.Dependencies, and is useful for accessing the field via an interface.
func (v *BranchSpecInput) GetDependencies() []*DependencySpecInput { return v.Dependencies }

// GetDependencyPatterns returns BranchSpecInput.DependencyPatterns, and is useful for accessing the field via an interface.
func (v *BranchSpecInput) GetDependencyPatterns() []*DependencyPatternSpecInput {
	return v.DependencyPatterns
}

// Controls whether non-base branches append a branch-derived suffix to
// semver, four-part, and calver versions.
// - APPEND: append branch namespace (e.g., 1.2.3-feat_x)
// - NO_APPEND: do not append; conflicts resolved via -0, -1, ... suffix
// - APPEND_EXCEPT_FOLLOW_VERSION: append for all branches and feature sets,
// except those with at least one follow-version dependency (treated as NO_APPEND for such branches)
// - INHERIT: component-level only; defer to organization setting. Not valid at organization level.
type BranchSuffixMode string

const (
	BranchSuffixModeAppend                    BranchSuffixMode = "APPEND"
	BranchSuffixModeNoAppend                  BranchSuffixMode = "NO_APPEND"
	BranchSuffixModeAppendExceptFollowVersion BranchSuffixMode = "APPEND_EXCEPT_FOLLOW_VERSION"
	BranchSuffixModeInherit                   BranchSuffixMode = "INHERIT"
)

var AllBranchSuffixMode = []BranchSuffixMode{
	BranchSuffixModeAppend,
	BranchSuffixModeNoAppend,
	BranchSuffixModeAppendExceptFollowVersion,
	BranchSuffixModeInherit,
}

type BranchType string

const (
	BranchTypeBase        BranchType = "BASE"
	BranchTypeFeature     BranchType = "FEATURE"
	BranchTypeRegular     BranchType = "REGULAR"
	BranchTypeRelease     BranchType = "RELEASE"
	BranchTypePullRequest BranchType = "PULL_REQUEST"
	BranchTypeTag         BranchType = "TAG"
	BranchTypeDevelop     BranchType = "DEVELOP"
	BranchTypeHotfix      BranchType = "HOTFIX"
)

var AllBranchType = []BranchType{
	BranchTypeBase,
	BranchTypeFeature,
	BranchTypeRegular,
	BranchTypeRelease,
	BranchTypePullRequest,
	BranchTypeTag,
	BranchTypeDevelop,
	BranchTypeHotfix,
}

// Branches slice: branches of a component, or feature sets of a product. The file is authoritative for that component.
type BranchesSpecInput struct {
	// Must be BRANCHES; the file's kind is validated against the operation.
	Kind    DeclarativeKind `json:"kind"`
	Version int             `json:"version"`
	// Component or product name.
	Component string `json:"component"`
	// When true (the default for files) the spec claims every non-base branch of the component and
	// Settings.declarativePrune decides what happens to branches it does not list. Single-branch
	// callers such as the Terraform provider pass false.
	Authoritative *bool              `json:"authoritative"`
	Branches      []*BranchSpecInput `json:"branches,omitempty"`
}

// GetKind returns BranchesSpecInput.Kind, and is useful for accessing the field via an interface.
func (v *BranchesSpecInput) GetKind() DeclarativeKind { return v.Kind }

// GetVersion returns BranchesSpecInput.Version, and is useful for accessing the field via an interface.
func (v *BranchesSpecInput) GetVersion() int { return v.Version }

// GetComponent returns BranchesSpecInput.Component, and is useful for accessing the field via an interface.
func (v *BranchesSpecInput) GetComponent() string { return v.Component }

// GetAuthoritative returns BranchesSpecInput.Authoritative, and is useful for accessing the field via an interface.
func (v *BranchesSpecInput) GetAuthoritative() *bool { return v.Authoritative }

// GetBranches returns BranchesSpecInput.Branches, and is useful for accessing the field via an interface.
func (v *BranchesSpecInput) GetBranches() []*BranchSpecInput { return v.Branches }

type CatalogComponentInput struct {
	Name                    string         `json:"name"`
	Type                    ComponentType  `json:"type"`
	Kind                    *ComponentKind `json:"kind"`
	VersionSchema           *string        `json:"versionSchema"`
	MarketingVersionSchema  *string        `json:"marketingVersionSchema"`
	VersionType             *VersionType   `json:"versionType"`
	FeatureBranchVersioning *string        `json:"featureBranchVersioning"`
	// Base branch name on create only (main by default).
	DefaultBranch *string `json:"defaultBranch"`
	// VCS repository by URI; created in the org when missing.
	VcsUri           *string            `json:"vcsUri"`
	VcsType          *string            `json:"vcsType"`
	RepoPath         *string            `json:"repoPath"`
	Nature           *ComponentNature   `json:"nature"`
	DeviceClass      *DeviceClass       `json:"deviceClass"`
	BranchSuffixMode *BranchSuffixMode  `json:"branchSuffixMode"`
	Identifiers      []*IdentifierInput `json:"identifiers,omitempty"`
}

// GetName returns CatalogComponentInput.Name, and is useful for accessing the field via an interface.
func (v *CatalogComponentInput) GetName() string { return v.Name }

// GetType returns CatalogComponentInput.Type, and is useful for accessing the field via an interface.
func (v *CatalogComponentInput) GetType() ComponentType { return v.Type }

// GetKind returns CatalogComponentInput.Kind, and is useful for accessing the field via an interface.
func (v *CatalogComponentInput) GetKind() *ComponentKind { return v.Kind }

// GetVersionSchema returns CatalogComponentInput.VersionSchema, and is useful for accessing the field via an interface.
func (v *CatalogComponentInput) GetVersionSchema() *string { return v.VersionSchema }

// GetMarketingVersionSchema returns CatalogComponentInput.MarketingVersionSchema, and is useful for accessing the field via an interface.
func (v *CatalogComponentInput) GetMarketingVersionSchema() *string { return v.MarketingVersionSchema }

// GetVersionType returns CatalogComponentInput.VersionType, and is useful for accessing the field via an interface.
func (v *CatalogComponentInput) GetVersionType() *VersionType { return v.VersionType }

// GetFeatureBranchVersioning returns CatalogComponentInput.FeatureBranchVersioning, and is useful for accessing the field via an interface.
func (v *CatalogComponentInput) GetFeatureBranchVersioning() *string {
	return v.FeatureBranchVersioning
}

// GetDefaultBranch returns CatalogComponentInput.DefaultBranch, and is useful for accessing the field via an interface.
func (v *CatalogComponentInput) GetDefaultBranch() *string { return v.DefaultBranch }

// GetVcsUri returns CatalogComponentInput.VcsUri, and is useful for accessing the field via an interface.
func (v *CatalogComponentInput) GetVcsUri() *string { return v.VcsUri }

// GetVcsType returns CatalogComponentInput.VcsType, and is useful for accessing the field via an interface.
func (v *CatalogComponentInput) GetVcsType() *string { return v.VcsType }

// GetRepoPath returns CatalogComponentInput.RepoPath, and is useful for accessing the field via an interface.
func (v *CatalogComponentInput) GetRepoPath() *string { return v.RepoPath }

// GetNature returns CatalogComponentInput.Nature, and is useful for accessing the field via an interface.
func (v *CatalogComponentInput) GetNature() *ComponentNature { return v.Nature }

// GetDeviceClass returns CatalogComponentInput.DeviceClass, and is useful for accessing the field via an interface.
func (v *CatalogComponentInput) GetDeviceClass() *DeviceClass { return v.DeviceClass }

// GetBranchSuffixMode returns CatalogComponentInput.BranchSuffixMode, and is useful for accessing the field via an interface.
func (v *CatalogComponentInput) GetBranchSuffixMode() *BranchSuffixMode { return v.BranchSuffixMode }

// GetIdentifiers returns CatalogComponentInput.Identifiers, and is useful for accessing the field via an interface.
func (v *CatalogComponentInput) GetIdentifiers() []*IdentifierInput { return v.Identifiers }

// Catalog slice: components and products of an organization (no branches, no releases).
type CatalogSpecInput struct {
	// Must be CATALOG; the file's kind is validated against the operation.
	Kind    DeclarativeKind `json:"kind"`
	Version int             `json:"version"`
	// When true the file claims every active component / product of the org: with
	// Settings.declarativePrune = ARCHIVE, components not listed are archived. Partial
	// files (per team) leave this false.
	Authoritative *bool                    `json:"authoritative"`
	Components    []*CatalogComponentInput `json:"components,omitempty"`
}

// GetKind returns CatalogSpecInput.Kind, and is useful for accessing the field via an interface.
func (v *CatalogSpecInput) GetKind() DeclarativeKind { return v.Kind }

// GetVersion returns CatalogSpecInput.Version, and is useful for accessing the field via an interface.
func (v *CatalogSpecInput) GetVersion() int { return v.Version }

// GetAuthoritative returns CatalogSpecInput.Authoritative, and is useful for accessing the field via an interface.
func (v *CatalogSpecInput) GetAuthoritative() *bool { return v.Authoritative }

// GetComponents returns CatalogSpecInput.Components, and is useful for accessing the field via an interface.
func (v *CatalogSpecInput) GetComponents() []*CatalogComponentInput { return v.Components }

// ChangeFields includes the GraphQL fields of DeclarativeChange requested by the fragment ChangeFields.
type ChangeFields struct {
	// Slice the entry belongs to: CATALOG entries are components, BRANCHES entries are branches.
	Kind   DeclarativeKind   `json:"kind"`
	Name   string            `json:"name"`
	Action DeclarativeAction `json:"action"`
	// Fields that differ (UPDATE) or would be set (CREATE).
	Fields  []string `json:"fields"`
	Message *string  `json:"message"`
}

// GetKind returns ChangeFields.Kind, and is useful for accessing the field via an interface.
func (v *ChangeFields) GetKind() DeclarativeKind { return v.Kind }

// GetName returns ChangeFields.Name, and is useful for accessing the field via an interface.
func (v *ChangeFields) GetName() string { return v.Name }

// GetAction returns ChangeFields.Action, and is useful for accessing the field via an interface.
func (v *ChangeFields) GetAction() DeclarativeAction { return v.Action }

// GetFields returns ChangeFields.Fields, and is useful for accessing the field via an interface.
func (v *ChangeFields) GetFields() []string { return v.Fields }

// GetMessage returns ChangeFields.Message, and is useful for accessing the field via an interface.
func (v *ChangeFields) GetMessage() *string { return v.Message }

type ComponentKind string

const (
	ComponentKindHelm    ComponentKind = "HELM"
	ComponentKindGeneric ComponentKind = "GENERIC"
)

var AllComponentKind = []ComponentKind{
	ComponentKindHelm,
	ComponentKindGeneric,
}

// Physical-ness axis of a component (Distribution module).
type ComponentNature string

const (
	ComponentNatureSoftware ComponentNature = "SOFTWARE"
	ComponentNatureHardware ComponentNature = "HARDWARE"
)

var AllComponentNature = []ComponentNature{
	ComponentNatureSoftware,
	ComponentNatureHardware,
}

type ComponentType string

const (
	ComponentTypeComponent ComponentType = "COMPONENT"
	ComponentTypeProduct   ComponentType = "PRODUCT"
	ComponentTypeAny       ComponentType = "ANY"
)

var AllComponentType = []ComponentType{
	ComponentTypeComponent,
	ComponentTypeProduct,
	ComponentTypeAny,
}

type DeclarativeAction string

const (
	DeclarativeActionCreate    DeclarativeAction = "CREATE"
	DeclarativeActionUpdate    DeclarativeAction = "UPDATE"
	DeclarativeActionUnchanged DeclarativeAction = "UNCHANGED"
	DeclarativeActionArchive   DeclarativeAction = "ARCHIVE"
	DeclarativeActionError     DeclarativeAction = "ERROR"
)

var AllDeclarativeAction = []DeclarativeAction{
	DeclarativeActionCreate,
	DeclarativeActionUpdate,
	DeclarativeActionUnchanged,
	DeclarativeActionArchive,
	DeclarativeActionError,
}

// Ownership slice a declarative spec describes. One kind per file; the apply / export operations are per kind.
type DeclarativeKind string

const (
	DeclarativeKindCatalog  DeclarativeKind = "CATALOG"
	DeclarativeKindBranches DeclarativeKind = "BRANCHES"
)

var AllDeclarativeKind = []DeclarativeKind{
	DeclarativeKindCatalog,
	DeclarativeKindBranches,
}

// Where an applied spec came from, recorded on every row the apply touched.
type DeclarativeSourceInput struct {
	Repo   *string `json:"repo"`
	Path   *string `json:"path"`
	Commit *string `json:"commit"`
}

// GetRepo returns DeclarativeSourceInput.Repo, and is useful for accessing the field via an interface.
func (v *DeclarativeSourceInput) GetRepo() *string { return v.Repo }

// GetPath returns DeclarativeSourceInput.Path, and is useful for accessing the field via an interface.
func (v *DeclarativeSourceInput) GetPath() *string { return v.Path }

// GetCommit returns DeclarativeSourceInput.Commit, and is useful for accessing the field via an interface.
func (v *DeclarativeSourceInput) GetCommit() *string { return v.Commit }

type DependencyPatternSpecInput struct {
	Pattern          string          `json:"pattern"`
	TargetBranchName *string         `json:"targetBranchName"`
	DefaultStatus    *Status         `json:"defaultStatus"`
	FallbackToBase   *FallbackToBase `json:"fallbackToBase"`
}

// GetPattern returns DependencyPatternSpecInput.Pattern, and is useful for accessing the field via an interface.
func (v *DependencyPatternSpecInput) GetPattern() string { return v.Pattern }

// GetTargetBranchName returns DependencyPatternSpecInput.TargetBranchName, and is useful for accessing the field via an interface.
func (v *DependencyPatternSpecInput) GetTargetBranchName() *string { return v.TargetBranchName }

// GetDefaultStatus returns DependencyPatternSpecInput.DefaultStatus, and is useful for accessing the field via an interface.
func (v *DependencyPatternSpecInput) GetDefaultStatus() *Status { return v.DefaultStatus }

// GetFallbackToBase returns DependencyPatternSpecInput.FallbackToBase, and is useful for accessing the field via an interface.
func (v *DependencyPatternSpecInput) GetFallbackToBase() *FallbackToBase { return v.FallbackToBase }

type DependencySpecInput struct {
	// Component name.
	Component string `json:"component"`
	// Branch name of that component; omitted = follow its base branch semantics as today.
	Branch *string `json:"branch"`
	// Pin to a release by version.
	Release         *string `json:"release"`
	Status          *Status `json:"status"`
	IsFollowVersion *bool   `json:"isFollowVersion"`
}

// GetComponent returns DependencySpecInput.Component, and is useful for accessing the field via an interface.
func (v *DependencySpecInput) GetComponent() string { return v.Component }

// GetBranch returns DependencySpecInput.Branch, and is useful for accessing the field via an interface.
func (v *DependencySpecInput) GetBranch() *string { return v.Branch }

// GetRelease returns DependencySpecInput.Release, and is useful for accessing the field via an interface.
func (v *DependencySpecInput) GetRelease() *string { return v.Release }

// GetStatus returns DependencySpecInput.Status, and is useful for accessing the field via an interface.
func (v *DependencySpecInput) GetStatus() *Status { return v.Status }

// GetIsFollowVersion returns DependencySpecInput.IsFollowVersion, and is useful for accessing the field via an interface.
func (v *DependencySpecInput) GetIsFollowVersion() *bool { return v.IsFollowVersion }

// Regulatory classification of a component / device (Distribution module).
type DeviceClass string

const (
	DeviceClassNone             DeviceClass = "NONE"
	DeviceClassMedicalUntracked DeviceClass = "MEDICAL_UNTRACKED"
	DeviceClassMedicalTracked   DeviceClass = "MEDICAL_TRACKED"
)

var AllDeviceClass = []DeviceClass{
	DeviceClassNone,
	DeviceClassMedicalUntracked,
	DeviceClassMedicalTracked,
}

// ExportBranchesExportBranchesProgrammaticBranchesSpec includes the requested fields of the GraphQL type BranchesSpec.
type ExportBranchesExportBranchesProgrammaticBranchesSpec struct {
	Kind          DeclarativeKind                                                                `json:"kind"`
	Version       int                                                                            `json:"version"`
	Component     string                                                                         `json:"component"`
	Authoritative bool                                                                           `json:"authoritative"`
	Branches      []*ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry `json:"branches"`
}

// GetKind returns ExportBranchesExportBranchesProgrammaticBranchesSpec.Kind, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpec) GetKind() DeclarativeKind {
	return v.Kind
}

// GetVersion returns ExportBranchesExportBranchesProgrammaticBranchesSpec.Version, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpec) GetVersion() int { return v.Version }

// GetComponent returns ExportBranchesExportBranchesProgrammaticBranchesSpec.Component, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpec) GetComponent() string {
	return v.Component
}

// GetAuthoritative returns ExportBranchesExportBranchesProgrammaticBranchesSpec.Authoritative, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpec) GetAuthoritative() bool {
	return v.Authoritative
}

// GetBranches returns ExportBranchesExportBranchesProgrammaticBranchesSpec.Branches, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpec) GetBranches() []*ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry {
	return v.Branches
}

// ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry includes the requested fields of the GraphQL type BranchSpecEntry.
type ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry struct {
	Name                          string                                                                                                            `json:"name"`
	Type                          *BranchType                                                                                                       `json:"type"`
	VersionSchema                 *string                                                                                                           `json:"versionSchema"`
	MarketingVersionSchema        *string                                                                                                           `json:"marketingVersionSchema"`
	VcsBranch                     *string                                                                                                           `json:"vcsBranch"`
	AutoIntegrate                 *AutoIntegrateState                                                                                               `json:"autoIntegrate"`
	FindingAnalyticsParticipation *FindingAnalyticsParticipation                                                                                    `json:"findingAnalyticsParticipation"`
	Dependencies                  []*ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependenciesDependencySpec          `json:"dependencies"`
	DependencyPatterns            []*ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependencyPatternsDependencyPattern `json:"dependencyPatterns"`
	Provenance                    *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryProvenanceDeclarativeProvenance       `json:"provenance"`
}

// GetName returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry.Name, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry) GetName() string {
	return v.Name
}

// GetType returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry.Type, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry) GetType() *BranchType {
	return v.Type
}

// GetVersionSchema returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry.VersionSchema, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry) GetVersionSchema() *string {
	return v.VersionSchema
}

// GetMarketingVersionSchema returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry.MarketingVersionSchema, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry) GetMarketingVersionSchema() *string {
	return v.MarketingVersionSchema
}

// GetVcsBranch returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry.VcsBranch, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry) GetVcsBranch() *string {
	return v.VcsBranch
}

// GetAutoIntegrate returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry.AutoIntegrate, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry) GetAutoIntegrate() *AutoIntegrateState {
	return v.AutoIntegrate
}

// GetFindingAnalyticsParticipation returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry.FindingAnalyticsParticipation, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry) GetFindingAnalyticsParticipation() *FindingAnalyticsParticipation {
	return v.FindingAnalyticsParticipation
}

// GetDependencies returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry.Dependencies, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry) GetDependencies() []*ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependenciesDependencySpec {
	return v.Dependencies
}

// GetDependencyPatterns returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry.DependencyPatterns, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry) GetDependencyPatterns() []*ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependencyPatternsDependencyPattern {
	return v.DependencyPatterns
}

// GetProvenance returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry.Provenance, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntry) GetProvenance() *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryProvenanceDeclarativeProvenance {
	return v.Provenance
}

// ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependenciesDependencySpec includes the requested fields of the GraphQL type DependencySpec.
type ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependenciesDependencySpec struct {
	Component       string  `json:"component"`
	Branch          *string `json:"branch"`
	Release         *string `json:"release"`
	Status          *Status `json:"status"`
	IsFollowVersion *bool   `json:"isFollowVersion"`
}

// GetComponent returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependenciesDependencySpec.Component, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependenciesDependencySpec) GetComponent() string {
	return v.Component
}

// GetBranch returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependenciesDependencySpec.Branch, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependenciesDependencySpec) GetBranch() *string {
	return v.Branch
}

// GetRelease returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependenciesDependencySpec.Release, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependenciesDependencySpec) GetRelease() *string {
	return v.Release
}

// GetStatus returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependenciesDependencySpec.Status, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependenciesDependencySpec) GetStatus() *Status {
	return v.Status
}

// GetIsFollowVersion returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependenciesDependencySpec.IsFollowVersion, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependenciesDependencySpec) GetIsFollowVersion() *bool {
	return v.IsFollowVersion
}

// ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependencyPatternsDependencyPattern includes the requested fields of the GraphQL type DependencyPattern.
type ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependencyPatternsDependencyPattern struct {
	Pattern          string          `json:"pattern"`
	TargetBranchName *string         `json:"targetBranchName"`
	DefaultStatus    Status          `json:"defaultStatus"`
	FallbackToBase   *FallbackToBase `json:"fallbackToBase"`
}

// GetPattern returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependencyPatternsDependencyPattern.Pattern, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependencyPatternsDependencyPattern) GetPattern() string {
	return v.Pattern
}

// GetTargetBranchName returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependencyPatternsDependencyPattern.TargetBranchName, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependencyPatternsDependencyPattern) GetTargetBranchName() *string {
	return v.TargetBranchName
}

// GetDefaultStatus returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependencyPatternsDependencyPattern.DefaultStatus, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependencyPatternsDependencyPattern) GetDefaultStatus() Status {
	return v.DefaultStatus
}

// GetFallbackToBase returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependencyPatternsDependencyPattern.FallbackToBase, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryDependencyPatternsDependencyPattern) GetFallbackToBase() *FallbackToBase {
	return v.FallbackToBase
}

// ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryProvenanceDeclarativeProvenance includes the requested fields of the GraphQL type DeclarativeProvenance.
type ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryProvenanceDeclarativeProvenance struct {
	ProvenanceFields `json:"-"`
}

// GetSpecHash returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryProvenanceDeclarativeProvenance.SpecHash, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryProvenanceDeclarativeProvenance) GetSpecHash() *string {
	return v.ProvenanceFields.SpecHash
}

// GetAppliedAt returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryProvenanceDeclarativeProvenance.AppliedAt, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryProvenanceDeclarativeProvenance) GetAppliedAt() *string {
	return v.ProvenanceFields.AppliedAt
}

// GetSource returns ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryProvenanceDeclarativeProvenance.Source, and is useful for accessing the field via an interface.
func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryProvenanceDeclarativeProvenance) GetSource() *ProvenanceFieldsSourceDeclarativeSource {
	return v.ProvenanceFields.Source
}

func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryProvenanceDeclarativeProvenance) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryProvenanceDeclarativeProvenance
		graphql.NoUnmarshalJSON
	}
	firstPass.ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryProvenanceDeclarativeProvenance = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.ProvenanceFields)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryProvenanceDeclarativeProvenance struct {
	SpecHash *string `json:"specHash"`

	AppliedAt *string `json:"appliedAt"`

	Source *ProvenanceFieldsSourceDeclarativeSource `json:"source"`
}

func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryProvenanceDeclarativeProvenance) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *ExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryProvenanceDeclarativeProvenance) __premarshalJSON() (*__premarshalExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryProvenanceDeclarativeProvenance, error) {
	var retval __premarshalExportBranchesExportBranchesProgrammaticBranchesSpecBranchesBranchSpecEntryProvenanceDeclarativeProvenance

	retval.SpecHash = v.ProvenanceFields.SpecHash
	retval.AppliedAt = v.ProvenanceFields.AppliedAt
	retval.Source = v.ProvenanceFields.Source
	return &retval, nil
}

// ExportBranchesResponse is returned by ExportBranches on success.
type ExportBranchesResponse struct {
	// Export the Branches slice of one component / product as a spec (CONFIGURATION_READ).
	ExportBranchesProgrammatic *ExportBranchesExportBranchesProgrammaticBranchesSpec `json:"exportBranchesProgrammatic"`
}

// GetExportBranchesProgrammatic returns ExportBranchesResponse.ExportBranchesProgrammatic, and is useful for accessing the field via an interface.
func (v *ExportBranchesResponse) GetExportBranchesProgrammatic() *ExportBranchesExportBranchesProgrammaticBranchesSpec {
	return v.ExportBranchesProgrammatic
}

// ExportCatalogExportCatalogProgrammaticCatalogSpec includes the requested fields of the GraphQL type CatalogSpec.
type ExportCatalogExportCatalogProgrammaticCatalogSpec struct {
	Kind          DeclarativeKind                                                                `json:"kind"`
	Version       int                                                                            `json:"version"`
	Authoritative bool                                                                           `json:"authoritative"`
	Components    []*ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent `json:"components"`
}

// GetKind returns ExportCatalogExportCatalogProgrammaticCatalogSpec.Kind, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpec) GetKind() DeclarativeKind { return v.Kind }

// GetVersion returns ExportCatalogExportCatalogProgrammaticCatalogSpec.Version, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpec) GetVersion() int { return v.Version }

// GetAuthoritative returns ExportCatalogExportCatalogProgrammaticCatalogSpec.Authoritative, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpec) GetAuthoritative() bool {
	return v.Authoritative
}

// GetComponents returns ExportCatalogExportCatalogProgrammaticCatalogSpec.Components, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpec) GetComponents() []*ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent {
	return v.Components
}

// ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent includes the requested fields of the GraphQL type CatalogComponent.
type ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent struct {
	Name                    string                                                                                                      `json:"name"`
	Type                    ComponentType                                                                                               `json:"type"`
	Kind                    *ComponentKind                                                                                              `json:"kind"`
	VersionSchema           *string                                                                                                     `json:"versionSchema"`
	MarketingVersionSchema  *string                                                                                                     `json:"marketingVersionSchema"`
	VersionType             *VersionType                                                                                                `json:"versionType"`
	FeatureBranchVersioning *string                                                                                                     `json:"featureBranchVersioning"`
	VcsUri                  *string                                                                                                     `json:"vcsUri"`
	VcsType                 *string                                                                                                     `json:"vcsType"`
	RepoPath                *string                                                                                                     `json:"repoPath"`
	Nature                  *ComponentNature                                                                                            `json:"nature"`
	DeviceClass             *DeviceClass                                                                                                `json:"deviceClass"`
	BranchSuffixMode        *BranchSuffixMode                                                                                           `json:"branchSuffixMode"`
	Identifiers             []*ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentIdentifiersIdentifier         `json:"identifiers"`
	Provenance              *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentProvenanceDeclarativeProvenance `json:"provenance"`
}

// GetName returns ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent.Name, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent) GetName() string {
	return v.Name
}

// GetType returns ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent.Type, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent) GetType() ComponentType {
	return v.Type
}

// GetKind returns ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent.Kind, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent) GetKind() *ComponentKind {
	return v.Kind
}

// GetVersionSchema returns ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent.VersionSchema, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent) GetVersionSchema() *string {
	return v.VersionSchema
}

// GetMarketingVersionSchema returns ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent.MarketingVersionSchema, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent) GetMarketingVersionSchema() *string {
	return v.MarketingVersionSchema
}

// GetVersionType returns ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent.VersionType, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent) GetVersionType() *VersionType {
	return v.VersionType
}

// GetFeatureBranchVersioning returns ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent.FeatureBranchVersioning, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent) GetFeatureBranchVersioning() *string {
	return v.FeatureBranchVersioning
}

// GetVcsUri returns ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent.VcsUri, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent) GetVcsUri() *string {
	return v.VcsUri
}

// GetVcsType returns ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent.VcsType, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent) GetVcsType() *string {
	return v.VcsType
}

// GetRepoPath returns ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent.RepoPath, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent) GetRepoPath() *string {
	return v.RepoPath
}

// GetNature returns ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent.Nature, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent) GetNature() *ComponentNature {
	return v.Nature
}

// GetDeviceClass returns ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent.DeviceClass, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent) GetDeviceClass() *DeviceClass {
	return v.DeviceClass
}

// GetBranchSuffixMode returns ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent.BranchSuffixMode, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent) GetBranchSuffixMode() *BranchSuffixMode {
	return v.BranchSuffixMode
}

// GetIdentifiers returns ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent.Identifiers, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent) GetIdentifiers() []*ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentIdentifiersIdentifier {
	return v.Identifiers
}

// GetProvenance returns ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent.Provenance, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponent) GetProvenance() *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentProvenanceDeclarativeProvenance {
	return v.Provenance
}

// ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentIdentifiersIdentifier includes the requested fields of the GraphQL type Identifier.
type ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentIdentifiersIdentifier struct {
	IdType  *IdentifierType `json:"idType"`
	IdValue *string         `json:"idValue"`
}

// GetIdType returns ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentIdentifiersIdentifier.IdType, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentIdentifiersIdentifier) GetIdType() *IdentifierType {
	return v.IdType
}

// GetIdValue returns ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentIdentifiersIdentifier.IdValue, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentIdentifiersIdentifier) GetIdValue() *string {
	return v.IdValue
}

// ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentProvenanceDeclarativeProvenance includes the requested fields of the GraphQL type DeclarativeProvenance.
type ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentProvenanceDeclarativeProvenance struct {
	ProvenanceFields `json:"-"`
}

// GetSpecHash returns ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentProvenanceDeclarativeProvenance.SpecHash, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentProvenanceDeclarativeProvenance) GetSpecHash() *string {
	return v.ProvenanceFields.SpecHash
}

// GetAppliedAt returns ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentProvenanceDeclarativeProvenance.AppliedAt, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentProvenanceDeclarativeProvenance) GetAppliedAt() *string {
	return v.ProvenanceFields.AppliedAt
}

// GetSource returns ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentProvenanceDeclarativeProvenance.Source, and is useful for accessing the field via an interface.
func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentProvenanceDeclarativeProvenance) GetSource() *ProvenanceFieldsSourceDeclarativeSource {
	return v.ProvenanceFields.Source
}

func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentProvenanceDeclarativeProvenance) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentProvenanceDeclarativeProvenance
		graphql.NoUnmarshalJSON
	}
	firstPass.ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentProvenanceDeclarativeProvenance = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.ProvenanceFields)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentProvenanceDeclarativeProvenance struct {
	SpecHash *string `json:"specHash"`

	AppliedAt *string `json:"appliedAt"`

	Source *ProvenanceFieldsSourceDeclarativeSource `json:"source"`
}

func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentProvenanceDeclarativeProvenance) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *ExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentProvenanceDeclarativeProvenance) __premarshalJSON() (*__premarshalExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentProvenanceDeclarativeProvenance, error) {
	var retval __premarshalExportCatalogExportCatalogProgrammaticCatalogSpecComponentsCatalogComponentProvenanceDeclarativeProvenance

	retval.SpecHash = v.ProvenanceFields.SpecHash
	retval.AppliedAt = v.ProvenanceFields.AppliedAt
	retval.Source = v.ProvenanceFields.Source
	return &retval, nil
}

// ExportCatalogResponse is returned by ExportCatalog on success.
type ExportCatalogResponse struct {
	// Export the Catalog slice of the key's org as a spec (CONFIGURATION_READ); optionally only the named components.
	ExportCatalogProgrammatic *ExportCatalogExportCatalogProgrammaticCatalogSpec `json:"exportCatalogProgrammatic"`
}

// GetExportCatalogProgrammatic returns ExportCatalogResponse.ExportCatalogProgrammatic, and is useful for accessing the field via an interface.
func (v *ExportCatalogResponse) GetExportCatalogProgrammatic() *ExportCatalogExportCatalogProgrammaticCatalogSpec {
	return v.ExportCatalogProgrammatic
}

type FallbackToBase string

const (
	FallbackToBaseEnabled  FallbackToBase = "ENABLED"
	FallbackToBaseDisabled FallbackToBase = "DISABLED"
)

var AllFallbackToBase = []FallbackToBase{
	FallbackToBaseEnabled,
	FallbackToBaseDisabled,
}

type FindingAnalyticsParticipation string

const (
	FindingAnalyticsParticipationIncluded FindingAnalyticsParticipation = "INCLUDED"
	FindingAnalyticsParticipationExcluded FindingAnalyticsParticipation = "EXCLUDED"
)

var AllFindingAnalyticsParticipation = []FindingAnalyticsParticipation{
	FindingAnalyticsParticipationIncluded,
	FindingAnalyticsParticipationExcluded,
}

type IdentifierInput struct {
	IdType  *IdentifierType `json:"idType"`
	IdValue *string         `json:"idValue"`
}

// GetIdType returns IdentifierInput.IdType, and is useful for accessing the field via an interface.
func (v *IdentifierInput) GetIdType() *IdentifierType { return v.IdType }

// GetIdValue returns IdentifierInput.IdValue, and is useful for accessing the field via an interface.
func (v *IdentifierInput) GetIdValue() *string { return v.IdValue }

type IdentifierType string

const (
	IdentifierTypePurl               IdentifierType = "PURL"
	IdentifierTypeCpe                IdentifierType = "CPE"
	IdentifierTypeTei                IdentifierType = "TEI"
	IdentifierTypeComplianceDocument IdentifierType = "COMPLIANCE_DOCUMENT"
	IdentifierTypeUdi                IdentifierType = "UDI"
	IdentifierTypeUdiDi              IdentifierType = "UDI_DI"
	IdentifierTypeUdiPi              IdentifierType = "UDI_PI"
	IdentifierTypeSerial             IdentifierType = "SERIAL"
	IdentifierTypeLot                IdentifierType = "LOT"
	IdentifierTypeSwid               IdentifierType = "SWID"
	IdentifierTypeSwhid              IdentifierType = "SWHID"
	IdentifierTypeOmniborid          IdentifierType = "OMNIBORID"
	IdentifierTypeGtin               IdentifierType = "GTIN"
	IdentifierTypeGmn                IdentifierType = "GMN"
	IdentifierTypeMpn                IdentifierType = "MPN"
	IdentifierTypePartNumber         IdentifierType = "PART_NUMBER"
	IdentifierTypeModelNumber        IdentifierType = "MODEL_NUMBER"
	IdentifierTypeSku                IdentifierType = "SKU"
	IdentifierTypeAssetTag           IdentifierType = "ASSET_TAG"
	IdentifierTypeFccId              IdentifierType = "FCC_ID"
	IdentifierTypeImei               IdentifierType = "IMEI"
	IdentifierTypeMacAddress         IdentifierType = "MAC_ADDRESS"
)

var AllIdentifierType = []IdentifierType{
	IdentifierTypePurl,
	IdentifierTypeCpe,
	IdentifierTypeTei,
	IdentifierTypeComplianceDocument,
	IdentifierTypeUdi,
	IdentifierTypeUdiDi,
	IdentifierTypeUdiPi,
	IdentifierTypeSerial,
	IdentifierTypeLot,
	IdentifierTypeSwid,
	IdentifierTypeSwhid,
	IdentifierTypeOmniborid,
	IdentifierTypeGtin,
	IdentifierTypeGmn,
	IdentifierTypeMpn,
	IdentifierTypePartNumber,
	IdentifierTypeModelNumber,
	IdentifierTypeSku,
	IdentifierTypeAssetTag,
	IdentifierTypeFccId,
	IdentifierTypeImei,
	IdentifierTypeMacAddress,
}

// ProvenanceFields includes the GraphQL fields of DeclarativeProvenance requested by the fragment ProvenanceFields.
type ProvenanceFields struct {
	// SHA-256 of the canonical JSON of the spec that last touched this row.
	SpecHash  *string                                  `json:"specHash"`
	AppliedAt *string                                  `json:"appliedAt"`
	Source    *ProvenanceFieldsSourceDeclarativeSource `json:"source"`
}

// GetSpecHash returns ProvenanceFields.SpecHash, and is useful for accessing the field via an interface.
func (v *ProvenanceFields) GetSpecHash() *string { return v.SpecHash }

// GetAppliedAt returns ProvenanceFields.AppliedAt, and is useful for accessing the field via an interface.
func (v *ProvenanceFields) GetAppliedAt() *string { return v.AppliedAt }

// GetSource returns ProvenanceFields.Source, and is useful for accessing the field via an interface.
func (v *ProvenanceFields) GetSource() *ProvenanceFieldsSourceDeclarativeSource { return v.Source }

// ProvenanceFieldsSourceDeclarativeSource includes the requested fields of the GraphQL type DeclarativeSource.
type ProvenanceFieldsSourceDeclarativeSource struct {
	Repo   *string `json:"repo"`
	Path   *string `json:"path"`
	Commit *string `json:"commit"`
}

// GetRepo returns ProvenanceFieldsSourceDeclarativeSource.Repo, and is useful for accessing the field via an interface.
func (v *ProvenanceFieldsSourceDeclarativeSource) GetRepo() *string { return v.Repo }

// GetPath returns ProvenanceFieldsSourceDeclarativeSource.Path, and is useful for accessing the field via an interface.
func (v *ProvenanceFieldsSourceDeclarativeSource) GetPath() *string { return v.Path }

// GetCommit returns ProvenanceFieldsSourceDeclarativeSource.Commit, and is useful for accessing the field via an interface.
func (v *ProvenanceFieldsSourceDeclarativeSource) GetCommit() *string { return v.Commit }

type Status string

const (
	StatusActive    Status = "ACTIVE"
	StatusApproved  Status = "APPROVED"
	StatusArchived  Status = "ARCHIVED"
	StatusComplete  Status = "COMPLETE"
	StatusDraft     Status = "DRAFT"
	StatusIgnored   Status = "IGNORED"
	StatusJob       Status = "JOB"
	StatusOptional  Status = "OPTIONAL"
	StatusPending   Status = "PENDING"
	StatusRejected  Status = "REJECTED"
	StatusRequired  Status = "REQUIRED"
	StatusTransient Status = "TRANSIENT"
)

var AllStatus = []Status{
	StatusActive,
	StatusApproved,
	StatusArchived,
	StatusComplete,
	StatusDraft,
	StatusIgnored,
	StatusJob,
	StatusOptional,
	StatusPending,
	StatusRejected,
	StatusRequired,
	StatusTransient,
}

type VersionType string

const (
	VersionTypeDev       VersionType = "DEV"
	VersionTypeMarketing VersionType = "MARKETING"
)

var AllVersionType = []VersionType{
	VersionTypeDev,
	VersionTypeMarketing,
}

// __ApplyBranchesInput is used internally by genqlient
type __ApplyBranchesInput struct {
	Spec   *BranchesSpecInput      `json:"spec,omitempty"`
	DryRun *bool                   `json:"dryRun"`
	Source *DeclarativeSourceInput `json:"source,omitempty"`
}

// GetSpec returns __ApplyBranchesInput.Spec, and is useful for accessing the field via an interface.
func (v *__ApplyBranchesInput) GetSpec() *BranchesSpecInput { return v.Spec }

// GetDryRun returns __ApplyBranchesInput.DryRun, and is useful for accessing the field via an interface.
func (v *__ApplyBranchesInput) GetDryRun() *bool { return v.DryRun }

// GetSource returns __ApplyBranchesInput.Source, and is useful for accessing the field via an interface.
func (v *__ApplyBranchesInput) GetSource() *DeclarativeSourceInput { return v.Source }

// __ApplyCatalogInput is used internally by genqlient
type __ApplyCatalogInput struct {
	Spec   *CatalogSpecInput       `json:"spec,omitempty"`
	DryRun *bool                   `json:"dryRun"`
	Source *DeclarativeSourceInput `json:"source,omitempty"`
}

// GetSpec returns __ApplyCatalogInput.Spec, and is useful for accessing the field via an interface.
func (v *__ApplyCatalogInput) GetSpec() *CatalogSpecInput { return v.Spec }

// GetDryRun returns __ApplyCatalogInput.DryRun, and is useful for accessing the field via an interface.
func (v *__ApplyCatalogInput) GetDryRun() *bool { return v.DryRun }

// GetSource returns __ApplyCatalogInput.Source, and is useful for accessing the field via an interface.
func (v *__ApplyCatalogInput) GetSource() *DeclarativeSourceInput { return v.Source }

// __ExportBranchesInput is used internally by genqlient
type __ExportBranchesInput struct {
	Component string `json:"component"`
}

// GetComponent returns __ExportBranchesInput.Component, and is useful for accessing the field via an interface.
func (v *__ExportBranchesInput) GetComponent() string { return v.Component }

// __ExportCatalogInput is used internally by genqlient
type __ExportCatalogInput struct {
	Components []string `json:"components"`
}

// GetComponents returns __ExportCatalogInput.Components, and is useful for accessing the field via an interface.
func (v *__ExportCatalogInput) GetComponents() []string { return v.Components }

// The mutation executed by ApplyBranches.
const ApplyBranches_Operation = `
mutation ApplyBranches ($spec: BranchesSpecInput!, $dryRun: Boolean, $source: DeclarativeSourceInput) {
	applyBranchesProgrammatic(spec: $spec, dryRun: $dryRun, source: $source) {
		... ApplyResultFields
	}
}
fragment ApplyResultFields on DeclarativeApplyResult {
	kind
	dryRun
	specHash
	created
	updated
	unchanged
	archived
	errors
	changes {
		... ChangeFields
	}
}
fragment ChangeFields on DeclarativeChange {
	kind
	name
	action
	fields
	message
}
`

func ApplyBranches(
	ctx_ context.Context,
	client_ graphql.Client,
	spec *BranchesSpecInput,
	dryRun *bool,
	source *DeclarativeSourceInput,
) (data_ *ApplyBranchesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ApplyBranches",
		Query:  ApplyBranches_Operation,
		Variables: &__ApplyBranchesInput{
			Spec:   spec,
			DryRun: dryRun,
			Source: source,
		},
	}

	data_ = &ApplyBranchesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by ApplyCatalog.
const ApplyCatalog_Operation = `
mutation ApplyCatalog ($spec: CatalogSpecInput!, $dryRun: Boolean, $source: DeclarativeSourceInput) {
	applyCatalogProgrammatic(spec: $spec, dryRun: $dryRun, source: $source) {
		... ApplyResultFields
	}
}
fragment ApplyResultFields on DeclarativeApplyResult {
	kind
	dryRun
	specHash
	created
	updated
	unchanged
	archived
	errors
	changes {
		... ChangeFields
	}
}
fragment ChangeFields on DeclarativeChange {
	kind
	name
	action
	fields
	message
}
`

func ApplyCatalog(
	ctx_ context.Context,
	client_ graphql.Client,
	spec *CatalogSpecInput,
	dryRun *bool,
	source *DeclarativeSourceInput,
) (data_ *ApplyCatalogResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ApplyCatalog",
		Query:  ApplyCatalog_Operation,
		Variables: &__ApplyCatalogInput{
			Spec:   spec,
			DryRun: dryRun,
			Source: source,
		},
	}

	data_ = &ApplyCatalogResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ExportBranches.
const ExportBranches_Operation = `
query ExportBranches ($component: String!) {
	exportBranchesProgrammatic(component: $component) {
		kind
		version
		component
		authoritative
		branches {
			name
			type
			versionSchema
			marketingVersionSchema
			vcsBranch
			autoIntegrate
			findingAnalyticsParticipation
			dependencies {
				component
				branch
				release
				status
				isFollowVersion
			}
			dependencyPatterns {
				pattern
				targetBranchName
				defaultStatus
				fallbackToBase
			}
			provenance {
				... ProvenanceFields
			}
		}
	}
}
fragment ProvenanceFields on DeclarativeProvenance {
	specHash
	appliedAt
	source {
		repo
		path
		commit
	}
}
`

func ExportBranches(
	ctx_ context.Context,
	client_ graphql.Client,
	component string,
) (data_ *ExportBranchesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ExportBranches",
		Query:  ExportBranches_Operation,
		Variables: &__ExportBranchesInput{
			Component: component,
		},
	}

	data_ = &ExportBranchesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ExportCatalog.
const ExportCatalog_Operation = `
query ExportCatalog ($components: [String!]) {
	exportCatalogProgrammatic(components: $components) {
		kind
		version
		authoritative
		components {
			name
			type
			kind
			versionSchema
			marketingVersionSchema
			versionType
			featureBranchVersioning
			vcsUri
			vcsType
			repoPath
			nature
			deviceClass
			branchSuffixMode
			identifiers {
				idType
				idValue
			}
			provenance {
				... ProvenanceFields
			}
		}
	}
}
fragment ProvenanceFields on DeclarativeProvenance {
	specHash
	appliedAt
	source {
		repo
		path
		commit
	}
}
`

func ExportCatalog(
	ctx_ context.Context,
	client_ graphql.Client,
	components []string,
) (data_ *ExportCatalogResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ExportCatalog",
		Query:  ExportCatalog_Operation,
		Variables: &__ExportCatalogInput{
			Components: components,
		},
	}

	data_ = &ExportCatalogResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
